name: Deploy

on:
  push:
    branches:
      - main  # Adjust to match your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Grant write access for commits
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full Git history

      - name: Install Dependencies
        run: npm install  # Ensure dependencies are installed

      - name: Run Elocuent
        run: |
          npx elocuent -d . -o meta/loc.csv

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p meta
          git pull
          git add -f meta/loc.csv
          git commit -m "Update code statistics" || echo "No changes to commit"
          git push
