name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install Elocuent
        run: npm install elocuent

      - name: Run Elocuent
        run: |
          mkdir -p meta
          npx elocuent -d . -o meta/loc.csv

      - name: Commit and Push
        run: |
          git config --global --add safe.directory /github/workspace
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add -f meta/loc.csv  # Keep the -f flag to force-add
          git commit -m "Update code statistics" || echo "No changes to commit"
          git push
